u = np.array([5, 1, 3])
m1 = np.array([4, 5, 1])
m2 = np.array([5, 1, 5])
print(np.dot(u, m1) / (np.linalg.norm(u) * np.linalg.norm(m1)))  
print(np.dot(u, m2) / (np.linalg.norm(u) * np.linalg.norm(m2)))  